In [1]:
import numpy as np

In [2]:
arr1 = np.array([0, 1, 3])

In [3]:
print(arr1)
print(arr1.shape)

print(f'{arr1}\n{"object type:":>12} {type(arr1)}\n{"data type:":>12} {arr1.dtype}\n{"shape:":>12} \
{arr1.shape}\n{"dimension:":>12} {arr1.ndim}\n{"array size:":>12} {arr1.size}')

[0 1 3]
(3,)
[0 1 3]
object type: <class 'numpy.ndarray'>
  data type: int64
      shape: (3,)
  dimension: 1
 array size: 3


In [4]:
arr2 = np.array([0,1,3])

In [5]:
a = arr1 + arr2
print(a)

[0 2 6]


In [6]:
arr3 = np.array([10.0, 0, 1])

In [7]:
print(f'{arr3}\n{"object type:":>12} {type(arr3)}\n{"data type:":>12} {arr3.dtype}\n{"shape:":>12} \
{arr3.shape}\n{"dimension:":>12} {arr3.ndim}\n{"array size:":>12} {arr3.size}')

[10.  0.  1.]
object type: <class 'numpy.ndarray'>
  data type: float64
      shape: (3,)
  dimension: 1
 array size: 3
